# frozen_string_literal: true

directories %w[. ../lib]

guard "rack", port: 9292 do
  watch("Gemfile.lock")
  watch(%r{\.rb$})
end

guard "livereload", grace_period: 1 do
  watch(%r{\.(erb|slim|rb)$})
end
